version: "3.7"
services:
  app:
    ports:
      - '3000:3000'
    environment:
      RACK_ENV:                 "development"
      RAILS_ENV:                "development"
    build: ./
    volumes:
      - ./:/app/
